---
title: "Untitled"
author: "Shelly Trigg"
date: "11/7/2019"
output: html_document
---

```{r}

amb_sites <- read.table("/Volumes/web/metacarcinus/Pgenerosa/analyses/20191024/amb_AllTimes_DMR250bp_MCmax30_cov5x_rms_results.tsv",header = TRUE, sep = "\t", stringsAsFactors = FALSE, quote = "", fill = FALSE)

nrow(amb_sites)
#[1] 913955

#test for loop on first 10 lines of data
test_amb_sites_filtered <- data.frame()
for (i in 1:10){
  print(i)
  f <- amb_sites[i,]
  if(length(which(amb_sites[i,22:25]!=-1))>=3 & length(which(amb_sites[i,26:29]!=-1))>=3 & length(which(amb_sites[i,30:33]!=-1))>=3 & length(which(amb_sites[i,34:37]!=-1))>=3){
    test_amb_sites_filtered <- rbind(test_amb_sites_filtered,f)
  }
}


amb_sites_filtered <- data.frame()
for (i in 1:nrow(amb_sites)){
  print(i)
  d <- amb_sites[i,]
  if(length(which(amb_sites[i,22:25]!=-1))>=3 & length(which(amb_sites[i,26:29]!=-1))>=3 & length(which(amb_sites[i,30:33]!=-1))>=3 & length(which(amb_sites[i,34:37]!=-1))>=3){
    amb_sites_filtered <- rbind(amb_sites_filtered,d)
  }
}
amb_sites_bed <- amb_sites_filtered[,c(1,2,2,5)] 
write.table(amb_sites_bed, "amb_sites_0.75XgroupCov.bed", quote = FALSE, row.names = FALSE, col.names = FALSE)


```


```{r}
day10_sites <- read.table("/Volumes/web/metacarcinus/Pgenerosa/analyses/20191024/day10_AllpH_DMR250bp_MCmax30_cov5x_rms_results.tsv",header = TRUE, sep = "\t", stringsAsFactors = FALSE, quote = "", fill = FALSE)

nrow(day10_sites)
#[1] 1013409
day10_sites_filtered <- data.frame()
for (i in 1:nrow(day10_sites)){
  print(i)
  d <- day10_sites[i,]
  if(length(which(day10_sites[i,22:25]!=-1))>=3 & length(which(day10_sites[i,26:29]!=-1))>=3 & length(which(day10_sites[i,30:33]!=-1))>=3 & length(which(day10_sites[i,34:37]!=-1))>=3){
    day10_sites_filtered <- rbind(day10_sites_filtered,d)
  }
}
day10_sites_bed <- day10_sites_filtered[,c(1,2,2,5)] 
write.table(day10_sites_bed, "day10_sites_0.75XgroupCov.bed", quote = FALSE, row.names = FALSE, col.names = FALSE)
```

```{r}
day135_sites <- read.table("/Volumes/web/metacarcinus/Pgenerosa/analyses/20191024/day135_AllpH_DMR250bp_MCmax30_cov5x_rms_results.tsv",header = TRUE, sep = "\t", stringsAsFactors = FALSE, quote = "", fill = FALSE)

nrow(day135_sites)
#[1] 502854
day135_sites_filtered <- data.frame()
for (i in 1:nrow(day135_sites)){
  print(i)
  d <- day135_sites[i,]
  if(length(which(day135_sites[i,22:25]!=-1))>=3 & length(which(day135_sites[i,26:29]!=-1))>=3 & length(which(day135_sites[i,30:33]!=-1))>=3 & length(which(day135_sites[i,34:37]!=-1))>=3){
    day135_sites_filtered <- rbind(day135_sites_filtered,d)
  }
}
day135_sites_bed <- day135_sites_filtered[,c(1,2,2,5)] 
write.table(day135_sites_bed, "day135_sites_0.75XgroupCov.bed", quote = FALSE, row.names = FALSE, col.names = FALSE)
```

```{r}
day145_sites <- read.table("/Volumes/web/metacarcinus/Pgenerosa/analyses/20191024/day145_AllpH_DMR250bp_MCmax30_cov5x_rms_results.tsv",header = TRUE, sep = "\t", stringsAsFactors = FALSE, quote = "", fill = FALSE)

nrow(day145_sites)
#[1] 897428
day145_sites_filtered <- data.frame()
for (i in 1:nrow(day145_sites)){
  print(i)
  d <- day145_sites[i,]
  if(length(which(day145_sites[i,22:25]!=-1))>=3 & length(which(day145_sites[i,26:29]!=-1))>=3 & length(which(day145_sites[i,30:33]!=-1))>=3 & length(which(day145_sites[i,34:37]!=-1))>=3){
    day145_sites_filtered <- rbind(day145_sites_filtered,d)
  }
}
day145_sites_bed <- day145_sites_filtered[,c(1,2,2,5)] 
write.table(day145_sites_bed, "day145_sites_0.75XgroupCov.bed", quote = FALSE, row.names = FALSE, col.names = FALSE)
```